language: node_js

node_js: stable

env:
  global:
    - secure: "eg05FK8zitTemfTO8fnMihIhgwd5UOKTc/x/a/mATllVutLnsLTdHAf/vh33FDzhNToeQ+k+wHDxsTMDhk9nTF1LpuOJ5Q+kMAvHn59b9dQVM/8/slhB60nEmVa2Sl3jMRjxXLHSdQO79FiHI/OqdzQ+7HZ/LaEMN4J5VxRtx2KPaeypaO159C8S6+EQtyUatCc89nt5OFAh5bmSM2YWvVlwdgQ+7mYaIbQRi2WWID5VziNfHVD/51ekdeyWo5UHhQKjJhvV9nh1L2Ze4sWdfkale7424FUJ9iiJefAEbgpXVEJl1PoXGGShASXX36aIpkiP/qkXjnGKcuwuKO5wSpsgYqnUvTMTkw/c6juntQ7vhLAxO5wN9qqeMfAU+UhYegp0DOQ1v0L1PSi3K8TZrqhH7pUqI/K8+z0VoJWl3EL2+aEpenfoSfaar0rY0pF5FbDIpiReQnEmNgYa2Urhm+C0xr9caSOMqP+uw+osDg0LOHc30yawPfjTdYQ1Cv5hnmpRRMR0yDh6I88PnrBqSQVAN8jsk5oBCp29fpXwRQip1/SFYD3BgCzidkvDRdJy8iYYSTR6itn+usSJiISai0JOZxfyKLz3Sue3ZsAk++CevCkKluuq2HST+T1KI7zrkxExed0Fe2cEnQ/3D8FM+PMc8UVpRRkcQJ+V4fVkF6I="

cache:
  apt: true
  directories:
   - node_modules

branches:
  only:
   - master

before_install:
  - npm install hexo-cli -g

install:
  - npm install
  - $(npm bin)/set-up-ssh --key "$encrypted_b9b50c5e0ab8_key" --iv "$encrypted_b9b50c5e0ab8_iv" --path-encrypted-key "id_rsa.enc"

before_script:
  - git config --global user.name ${GH_USER_NAME}
  - git config --global user.email ${GH_USER_EMAIL}

script:
  - hexo generate
  - hexo deploy
