# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
  favicon: https://cat.yufan.me/asserts/spectre/images/favicon.png
  high_res_favicon: https://cat.yufan.me/asserts/spectre/images/favicon.png
  apple_touch_icon: https://cat.yufan.me/asserts/spectre/images/favicon.png
  keywords: "雨帆, 且听书吟"
  site_verification:
    google:
    baidu:

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Theme Color
color:
  android_chrome_color: "#455A64"

# ---------------------------------------------------------------
# Customsize Settings
# ---------------------------------------------------------------

# Jump Links Settings
url:
  rss: /rss.xml
  daily_pic: ""
  logo: "https://yufan.me"

# Images Settings
img:
  logo: https://cat.yufan.me/asserts/spectre/images/avatar.jpg
  avatar: https://cat.yufan.me/asserts/spectre/images/avatar.jpg
  daily_pic: https://cat.yufan.me/asserts/spectre/images/banner.jpg

# Slogan (will show at daily_pic)
slogan: "我思 我说 我写"

# Posts Settings
post:
  entry_excerpt: 120

  # Qrcode for redirect at other device
  #    use: choose which method to generate the qrcode for each posts.
  #        Available value: plugin | online
  #            - When use "plugin", you need to install the hexo-helper-qrcode.
  #            - When use "online", the qrcode will be generated by 'pan.baidu.com' in Mainland China,
  #               and generated by 'charts.googleapis.com' in other areas.
  qrcode:
    enable: true
    use: plugin

  # Post License
  # You can specify the text you want to show in the end of your posts and pages, HTML tag is supported.
  #   For example, you can setup a CC license as:
  #       'This blog is under a <a href="/creativecommons.html" target="_blank">CC BY-NC-SA 3.0 Unported License</a>'
  # You can also use Front-Matter `license` to override this setting.
  # license: "本文采用 <a rel='nofollow noopener' href='https://creativecommons.org/licenses/by-nc-sa/3.0/deed.zh' target='_blank'>CC BY-NC-SA 3.0 Unported</a> 协议进行许可，阅读 <a href='/creativecommons.html' target='_blank'>相关说明</a>"

  # TOC Button
  toc:
  # use: choose whether the line_number of toc will show or not.
  #   Available value of "linenumber": true | false
    linenumber: true

# Footer Settings
footer:
  # Footer Copyright
  # Specify the date when the site was setup.
  #    For example, if you set it as 2015, then footer will show '© 2015 - 2017'
  copyright_since: 2011
  footer_text: '<div><a href="http://www.miitbeian.gov.cn" rel="nofollow">闽ICP备12017112号-1</a></div>'

  # FooterSNS Icon
  sns:
    github: https://github.com/syhily
    twitter: https://twitter.com/syhily
    telegram: https://t.me/syhily
    facebook: https://www.facebook.com/syhily
    googleplus:
    weibo:
    instagram:
    tumblr:
    linkedin:
    zhihu:
    bilibili:
    v2ex:

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# SNS Share Switch
sns_share:
  twitter: true
  facebook: true
  googleplus: true
  weibo: false
  linkedin: false
  qq: false
  telegram: true

# Sidebar Customize
sidebar:
  homepage:
    use: true
    icon: home
    divider: false
  search:
    use: true
    icon: search
    divider: false
  archives:
    use: true
    icon: inbox
    divider: false
  categories:
    use: false
    icon: chrome_reader_mode
    divider: false
  pages:
    标签:
      link: "/tags"
      icon: bookmark
      divider: false
    关于:
      link: "/about"
      icon: person
      divider: false
    映像:
      link: "/gallery"
      icon: photo
      divider: false
    友链:
      link: "/links"
      icon: people
      divider: true
  article_num:
    use: true
    divider: false
  # footer:
  #   upyun_logo:
  #     link: "https://www.upyun.com/"
  #     src: "https://s.nfz.yecdn.com/img/upyun_logo.svg"


# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------

# Comment Systems
# Available value of "use":
#   disqus | disqus_click | changyan | livere | gitment | valine
# If you want to use gitment,you should get the client_id and client_secret form https://github.com/settings/applications/new
# If you want to use valine,you should get the app_id and app_key form https://leancloud.cn ,more setting please see https://github.com/xCss/Valine
comment:
  use: disqus_click
  shortname: xiaoyu-1 # duoshuo or disqus shortname
  changyan_appid:
  changyan_conf:
  changyan_thread_key_type: path
  livere_data_uid:
  gitment_repo:   # git repo of the hexo
  gitment_owner:  # git repo's owner
  gitment_client_id:  # github app client id 
  gitment_client_secret :  # github app client secret 
  valine_leancloud_appId: # leancloud application app id
  valine_leancloud_appKey: # leancloud application app key

# Analytics Systems
# Available value:
#     baidu | google | cnzz
analytics:
  google_site_id:
  baidu_site_id:
  cnzz_site_id:
  tencent_analytics_id: 11315873

# Search Systems
search:
  use: true # true || false
  link: /search

# ---------------------------------------------------------------
# Do Not Edit Below This Line, unless you know what you are doing!
# ---------------------------------------------------------------
verison: 0.1.1
old_verison:
  - 0.1.0
